# Generated by Django 5.2.5 on 2025-08-27 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_carantin_ipwhitelistonoroff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('carantin_on', 'Карантин включен'), ('carantin_off', 'Карантин выключен'), ('error_503_on', 'Ошибка 503 включена'), ('error_503_off', 'Ошибка 503 выключена'), ('whitelist_on', 'Белый список включен'), ('whitelist_off', 'Белый список выключен')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
