# Generated by Django 5.2.5 on 2025-08-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_modelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_group_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
