# Generated by Django 5.2.5 on 2025-09-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_telegram_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
